---
- name: Download R
  get_url: >
    url="https://cran.r-project.org/bin/macosx/R-{{ r_version }}.pkg"
    dest="{{ downloads_directory }}/R-{{ r_version }}.pkg"

- name: Install R
  command: >
    chdir={{ downloads_directory }}
    installer -package "R-{{ r_version }}.pkg" -target /
  become: yes
