---
- name: Download PostgreSQL
  get_url: >
    url="{{ postgresql_image_url }}"
    dest="{{ postgresql_image_path }}"

- name: Get current PostgreSQL version
  shell: defaults read /Applications/Postgres.app/Contents/Info.plist CFBundleShortVersionString
  register: postgresql_version_output
  ignore_errors: yes

- name: Mount PostgreSQL image
  command: >
    hdiutil attach {{ postgresql_image_path }}
    creates="{{ postgresql_volume_path }}"
  when: postgresql_version_output.stdout | version_compare(postgresql_version, '<')

- name: Create {{ postgresql_app_directory }}
  command: >
    cp -R "{{ postgresql_volume_path }}/{{ postgresql_app_name }}" /Applications
  become: yes
  when: postgresql_version_output.stdout | version_compare(postgresql_version, '<')

- name: Unmount PostgreSQL image
  command: hdiutil detach "{{ postgresql_volume_path }}"
  when: postgresql_version_output.stdout | version_compare(postgresql_version, '<')
