---
- name: Download Stack
  get_url:
    url: "https://github.com/commercialhaskell/stack/releases/download/v{{ stack_version }}/stack-{{ stack_version }}-osx-x86_64.tar.gz"
    dest: "{{ downloads_directory }}/{{ stack_archive }}"

- command: mkdir -p "{{ downloads_directory }}/{{ stack_directory }}"

- name: Extract Stack
  unarchive:
    src="{{ downloads_directory }}/{{ stack_archive }}"
    dest="{{ downloads_directory }}"
    creates="{{ downloads_directory }}/{{ stack_directory }}/stack"

- name: Install Stack
  command: cp "{{ downloads_directory }}/{{ stack_directory }}/stack" /usr/local/bin
