---
- name: Install coreutils
  homebrew:
    name: coreutils
    state: latest

- name: Install some GNU tools
  homebrew:
    state: latest
    name:
      - binutils # don't link this so that there's no conflicts with macOS binaries.
      - diffutils
      - ed
      - findutils
      - gawk
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-which
      - gnutls
      - grep
      - gzip
      - screen
      - watch
      - wdiff
      - wget
