---
- name: Download MacVim
  get_url: >
    url=https://github.com/macvim-dev/macvim/releases/download/{{ macvim_version }}/MacVim.dmg
    dest={{ downloads_directory }}/MacVim-{{ macvim_version }}.dmg

- name: Mount MacVim image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse MacVim-{{ macvim_version }}.dmg
    creates=/Volumes/MacVim

- name: Install MacVim
  command: >
    cp -R /Volumes/MacVim/MacVim.app /Applications
  become: yes

- name: Unmount MacVim image
  command: hdiutil detach /Volumes/MacVim
