---
- name: Download Google Photos
  get_url:
    url: https://dl.google.com/dl/picasa/{{ google_photos_dmg }}
    dest: "{{ downloads_directory }}/{{ google_photos_dmg }}"

- name: Mount Google Photos image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse {{ google_photos_dmg }}
    creates="/Volumes/{{ google_photos_volume }}"

- name: Copy Google Photos application directory to the applications directory
  command: >
    cp -R "/Volumes/{{ google_photos_volume }}/{{ google_photos_app }}" /Applications
    creates="/Applications/{{ google_photos_app }}"

- name: Unmount Google Photos image
  command: hdiutil detach "/Volumes/{{ google_photos_volume }}"
