---
- name: Clone Cantata repository
  git:
    repo: "https://github.com/CDrummond/cantata.git"
    dest: "{{ downloads_directory }}/cantata"

- name: Clear build directory
  file: >
    path="{{ downloads_directory }}/cantata/build"
    state=absent

- name: Ensure build directory exists
  file: >
    path="{{ downloads_directory }}/cantata/build"
    state=directory

- name: Create Cantata Makefile
  shell: >
    chdir="{{ downloads_directory }}/cantata/build"
    CMAKE_PREFIX_PATH="/Applications/Qt{{ qt_version }}/{{ qt_major_minor_version }}/clang_64" cmake ..

- name: Build Cantata
  command:
    chdir="{{ downloads_directory }}/cantata/build"
    make

- name: Install Cantata
  command:
    chdir="{{ downloads_directory }}/cantata/build"
    make install
  become: yes
