---
- name: Download Firefox
  get_url:
    url: "https://download.mozilla.org/?product=firefox-{{ firefox_version }}&os=osx"
    dest: "{{ downloads_directory }}/Firefox.dmg"

- name: Get current Firefox version
  shell: defaults read "{{ firefox_app }}/Contents/Info.plist" CFBundleShortVersionString
  register: firefox_version_output
  ignore_errors: yes

- name: Maybe clear '{{ firefox_app }}' directory
  file: >
    path="{{ firefox_app }}"
    state=absent
  when: firefox_version_output.rc == 1

- name: Mount Firefox image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse Firefox.dmg
    creates=/Volumes/Firefox
  when: firefox_version_output.rc == 1

- name: Copy Firefox application directory to the applications directory
  command: >
    cp -R /Volumes/Firefox/Firefox.app /Applications
    creates={{ firefox_app }}
  when: firefox_version_output.rc == 1

- name: Unmount Firefox image
  command: hdiutil detach /Volumes/Firefox
  when: firefox_version_output.rc == 1
