---
- name: Download LightTable
  get_url: >
    url=https://github.com/LightTable/LightTable/releases/download/{{ light_table_version }}/lighttable-{{ light_table_version }}-mac.tar.gz
    dest={{ downloads_directory }}/lighttable-{{ light_table_version }}-mac.tar.gz

- name: Extract LightTable archive
  unarchive:
    src="{{ downloads_directory }}/lighttable-{{ light_table_version }}-mac.tar.gz"
    dest="{{ downloads_directory }}"
    creates="{{ downloads_directory }}/lighttable-{{ light_table_version }}-mac"

- name: Copy LightTable.app to Applications directory
  command: >
    cp -R {{ downloads_directory }}/lighttable-{{ light_table_version }}-mac/LightTable.app /Applications
    creates=/Applications/LightTable.app
  become: yes
