---
- name: Download Google Chrome
  get_url: >
    url="{{ google_chrome_image_url }}"
    dest="{{ google_chrome_image_path }}"

- name: Get {{ google_chrome_app_directory }} stats
  stat:
    path: "{{ google_chrome_app_directory }}"
  register: google_chrome_app_directory_stat

- name: Mount Google Chrome image
  command: >
    hdiutil attach -nobrowse {{ google_chrome_image_path }}
    creates="{{ google_chrome_volume_path }}"
  when: not google_chrome_app_directory_stat.stat.exists

- name: Get {{ google_chrome_volume_path }} stats
  stat:
    path: "{{ google_chrome_volume_path }}"
  register: google_chrome_volume_path_stat

- name: Create {{ google_chrome_app_directory }}
  command: >
    cp -R "{{ google_chrome_volume_path }}/{{ google_chrome_app_name }}" /Applications
    creates="{{ google_chrome_app_directory }}"
  become: yes

- name: Unmount Google Chrome image
  command: hdiutil detach "{{ google_chrome_volume_path }}"
  when: google_chrome_volume_path_stat.stat.exists
