---
- name: Download OpenOffice
  get_url: >
    url="http://archive.apache.org/dist/openoffice/{{ open_office_version }}/binaries/en-US/Apache_OpenOffice_{{ open_office_version }}_MacOS_x86-64_install_en-US.dmg"
    dest="{{ downloads_directory }}/Apache_OpenOffice_{{ open_office_version }}_MacOS_x86-64_install_en-US.dmg"

- name: Mount the OpenOffice image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse "Apache_OpenOffice_{{ open_office_version }}_MacOS_x86-64_install_en-US.dmg"
    creates=/Volumes/OpenOffice

- name: Install OpenOffice
  command: >
    cp -R /Volumes/OpenOffice/OpenOffice.app /Applications
    creates=/Applications/OpenOffice.app
  become: yes

- name: Unmount the OpenOffice image
  command: hdiutil detach /Volumes/OpenOffice
