---
- name: Download XQuartz
  get_url:
    url: "https://github.com/XQuartz/XQuartz/releases/download/XQuartz-{{ xquartz_version }}/{{ xquartz_dmg }}"
    dest: "{{ downloads_directory }}/{{ xquartz_dmg }}"


- name: Mount XQuartz image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse {{ xquartz_dmg }}
    creates=/Volumes/{{ xquartz_volume }}

- name: Install XQuartz
  command: >
    installer -package /Volumes/{{ xquartz_volume }}/XQuartz.pkg -target /
  become: yes

- name: Unmount XQuartz image
  command: hdiutil detach /Volumes/{{ xquartz_volume }}
