- name: Install awscli
  pip:
    name: awscli
    extra_args: --user

- name: Ensure ~/.aws directory exists
  file:
    path: "{{ home_directory }}/.aws"
    state: directory

- name: Install ~/.aws/credentials
  copy:
    content: "{{ aws_credentials_file_base64 | b64decode }}"
    dest: "{{ home_directory }}/.aws/credentials"
    mode: 0644
