---
- name: Install mpdscribble
  homebrew:
    name: mpdscribble
    state: latest

- name: Create mpdscribble service and start mpdscribble
  command: brew services restart mpdscribble
  ignore_errors: yes
