---
- name: Check out the mpereira/dotfiles repository
  git:
    repo: git@github.com:mpereira/dotfiles.git
    dest: "{{ home_directory }}/.dotfiles"
    update: no

- name: Install dotfiles
  environment: "{{ dotfiles_environment_yml_file_base64 | b64decode | from_yaml }}"
  shell: rake sync
  args:
    chdir: "{{ home_directory }}/.dotfiles"
