---
- name: Check out the mpereira/dotfiles repository
  git:
    repo: git@github.com:mpereira/dotfiles.git
    dest: "{{ home_directory }}/.dotfiles"
    update: no

- name: Load environment variables
  include_vars:
    file: "{{ mpereira_dotfiles_environment_yml_file }}"
    name: environment_variables
  no_log: yes

- name: Install dotfiles
  environment: "{{ environment_variables }}"
  shell: rake sync
  args:
    chdir: "{{ home_directory }}/.dotfiles"
