---
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh_directory }}"
    mode: 0700
    owner: "{{ user }}"
    state: directory

- name: Install private SSH key
  copy:
    src: "{{ mpereira_at_pluto_ssh_private_key }}"
    dest: "{{ ssh_directory }}/mpereira@pluto"
    mode: 0600
    owner: "{{ user }}"

- name: Install public SSH keys
  copy:
    src: "{{ item }}"
    dest: "{{ ssh_directory }}/{{ item }}"
    mode: 0644
    owner: "{{ user }}"
  loop:
    - "mpereira@argonaut.pub"
    - "mpereira@pluto.pub"

- name: Add authorized keys
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  loop:
    - "mpereira@argonaut.pub"
    - "mpereira@pluto.pub"
