---
- name: Download the Chef Development Kit
  get_url: >
    url=https://packages.chef.io/stable/mac_os_x/10.11/chefdk-0.10.0-1.dmg
    validate_certs=False
    dest={{ downloads_directory }}/chefdk-0.10.0-1.dmg

- name: Mount the Chef Development Kit image
  command: >
    chdir={{ downloads_directory }}
    creates="/Volumes/Chef Development Kit"
    hdiutil attach -nobrowse chefdk-0.10.0-1.dmg

- name: Install Chef Development Kit
  command: >
    installer -package /Volumes/Chef\ Development\ Kit/chefdk-0.10.0-1.pkg -target /
    creates=/usr/bin/chef
  become: yes

- name: Unmount the Chef Development Kit image
  command: hdiutil detach /Volumes/Chef\ Development\ Kit
