---
- name: Download BitBar
  get_url:
    url: https://github.com/matryer/bitbar/releases/download/v{{ bitbar_version }}/BitBar.app.zip
    dest: "{{ downloads_directory }}/BitBar.app.zip"

- name: Check existing BitBar version
  shell: "defaults read /Applications/BitBar.app/Contents/Info.plist CFBundleVersion --version 2>&1"
  register: bitbar_version_output
  ignore_errors: yes

- name: Extract BitBar zip archive
  command: >
    chdir="{{ downloads_directory }}"
    unzip BitBar.app.zip -d {{ bitbar_directory }}
    creates="{{ bitbar_directory }}"
  when: bitbar_version_output.stdout.find(bitbar_version) == -1

- name: Copy BitBar.app to Applications directory
  command: >
    cp -R "{{ downloads_directory }}/{{ bitbar_directory }}/BitBar.app" /Applications
    creates=/Applications/BitBar.app
  become: yes
  when: bitbar_version_output.stdout.find(bitbar_version) == -1
