---
- name: Download BitBar
  get_url:
    url: https://github.com/matryer/bitbar/releases/download/v{{ bitbar_version }}/{{ bitbar_zip }}
    dest: "{{ downloads_directory }}/{{ bitbar_zip }}"

- name: Check existing BitBar version
  shell: "defaults read /Applications/BitBar.app/Contents/Info.plist CFBundleVersion --version 2>&1"
  register: bitbar_version_output
  ignore_errors: yes

- name: Extract BitBar zip archive
  command: >
    chdir="{{ downloads_directory }}"
    unzip {{ bitbar_zip }} -d {{ bitbar_directory }}
    creates="{{ bitbar_directory }}"
  when: bitbar_version_output.stdout.find(bitbar_version) == -1

- name: Copy BitBar.app to Applications directory
  command: >
    cp -R "{{ downloads_directory }}/{{ bitbar_directory }}/BitBar.app" /Applications
    creates=/Applications/BitBar.app
  become: yes
  when: bitbar_version_output.stdout.find(bitbar_version) == -1

- name: Ensure the BitBar .config directory exists
  file: >
    path="{{ home_directory }}/.config/bitbar"
    state=directory

- name: Clone BitBar plugins repository
  git:
    repo: "git@github.com:mpereira/bitbar-plugins.git"
    dest: "{{ home_directory }}/.config/bitbar/plugins"

- name: Configure BitBar plugins directory
  command: >
    defaults write com.matryer.BitBar pluginsDirectory "{{ home_directory }}/.config/bitbar/plugins/Enabled"

- name: Install BitBar plugins
  file:
    src: "{{ home_directory }}/.config/bitbar/plugins/{{ item.src }}"
    dest: "{{ home_directory }}/.config/bitbar/plugins/Enabled/{{ item.dest }}"
    state: link
  with_items:
    - { src: 'Music/mpd-simple.5s.sh', dest: 'mpd-simple.2s.sh' }
    - { src: 'Music/spotify-simple.5s.sh', dest: 'spotify-simple.5s.sh' }
