---
- name: Download Hangouts
  get_url: >
    url=https://dl.google.com/googletalk/googletalkplugin/GoogleVoiceAndVideoSetup.dmg
    dest={{ downloads_directory }}/GoogleVoiceAndVideoSetup.dmg

- name: Mount Hangouts image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse GoogleVoiceAndVideoSetup.dmg
  register: mount_hangounts_image

- name: Get Hangouts version
  shell: >
    ls /Volumes | grep GoogleVoiceAndVideoAccelSetup | cut -d_ -f2
  register: hangouts_version

- name: Install Hangouts
  shell: >
    installer -package "/Volumes/GoogleVoiceAndVideoAccelSetup_{{ hangouts_version.stdout }}/Google Voice and Video.pkg" -target /
    creates="/Users/{{ user }}/Library/Application Support/Google/GoogleTalkPlugin.app"
  become: yes

- name: Unmount Hangouts image
  command: hdiutil detach /Volumes/GoogleVoiceAndVideoAccelSetup_{{ hangouts_version.stdout }}
