---
- name: Download LICEcap
  get_url:
    url: http://www.cockos.com/licecap/{{ licecap_dmg }}
    dest: "{{ downloads_directory }}/{{ licecap_dmg }}"

- name: Convert LICEcap image to a format that does not require an EULA
  command: >
    chdir={{ downloads_directory }}
    hdiutil convert -quiet {{ licecap_dmg }} -format UDTO -o licecap123
    creates={{ licecap_cdr }}

- name: Mount LICEcap image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach -nobrowse -quiet {{ licecap_cdr }}
    creates=/Volumes/{{ licecap_volume }}

- name: Copy {{ licecap_app }}lication directory to the applications directory
  command: >
    cp -R /Volumes/{{ licecap_volume }}/{{ licecap_app }} /Applications
    creates=/Applications/{{ licecap_app }}

- name: Unmount LICEcap image
  command: hdiutil detach /Volumes/{{ licecap_volume }}
