---
# NOTE: not using the Homebrew brew because it is hard-coded to depend on
# openjdk@11 from Homebrew.
- name: Install Clojure LSP
  get_url:
    url: https://github.com/snoe/clojure-lsp/releases/latest/download/clojure-lsp
    dest: /usr/local/bin/clojure-lsp
    mode: u+x
