---
- name: Check out the defaultbrowser repository
  git:
    repo: https://github.com/kerma/defaultbrowser.git
    dest: "{{ downloads_directory }}/defaultbrowser"
    version: "{{ defaultbrowser_version }}"

- name: Build defaultbrowser
  command: 
    cmd: make
    chdir: "{{ downloads_directory }}/defaultbrowser"

- name: Install defaultbrowser
  command: 
    cmd: make install
    chdir: "{{ downloads_directory }}/defaultbrowser"
