---
- name: Ensure the BitBar .config directory exists
  file: >
    path="{{ home_directory }}/.config/bitbar"
    state=directory

- name: Clone BitBar plugins repository
  git:
    repo: "git@github.com:mpereira/bitbar-plugins.git"
    dest: "{{ home_directory }}/.config/bitbar/plugins"

- name: Configure BitBar plugins directory
  command: >
    defaults write com.matryer.BitBar pluginsDirectory "{{ home_directory }}/.config/bitbar/plugins/Enabled"

- name: Install BitBar plugins
  file:
    src: "{{ home_directory }}/.config/bitbar/plugins/{{ item.src }}"
    dest: "{{ home_directory }}/.config/bitbar/plugins/Enabled/{{ item.dest }}"
    state: link
  with_items:
    - { src: 'Music/mpd-mpereira.5s.sh', dest: 'mpd-mpereira.5s.sh' }
    - { src: 'Music/spotify-mpereira.5s.sh', dest: 'spotify-mpereira.5s.sh' }
