---
- name: Add cask-fonts tap
  command: brew tap homebrew/cask-fonts

- name: Install Hack font
  homebrew_cask:
    name: font-hack
    state: latest

- name: Install fontconfig
  homebrew:
    name: fontconfig
    state: latest

- name: Reload fonts
  command: fc-cache -vf
  become: yes
