---
- name: Download Skitch
  get_url:
    url: https://evernote.s3.amazonaws.com/skitch/mac/release/{{ skitch_zip }}
    dest: "{{ downloads_directory }}/{{ skitch_zip }}"

- name: Extract Skitch zip archive
  command: >
    chdir={{ downloads_directory }}
    unzip {{ skitch_zip }} -d {{ skitch_directory }}
    creates={{ skitch_directory }}

- name: Copy {{ skitch_app }} to Applications directory
  command: >
    cp -R {{ downloads_directory }}/{{ skitch_directory }}//{{ skitch_app }} /Applications
    creates=/Applications/{{ skitch_app }}
  become: yes
