---
- name: Download {{ qt_image_url }}
  get_url: >
    url="{{ qt_image_url }}"
    dest="{{ qt_image_path }}"
    checksum="md5:3d940877ea3dd22c095463bcdf6aa966"

# 5.12.0:
# checksum="md5:6fe192b2b63bd0f3203266b677510a22"

- name: Get {{ qt_app_directory }} stats
  stat:
    path: "{{ qt_app_directory }}"
  register: qt_app_directory_stat

- name: Mount {{ qt_image_path }}
  command: >
    hdiutil attach -nobrowse -noverify {{ qt_image_path }}
    creates="{{ qt_volume_path }}"
  when: not qt_app_directory_stat.stat.exists

- name: Get {{ qt_volume_path }} stats
  stat:
    path: "{{ qt_volume_path }}"
  register: qt_volume_path_stat

- name: Create {{ qt_app_directory }}
  command: >
    cp -R "{{ qt_volume_path }}/{{ qt_app_name }}" /Applications
    creates="{{ qt_app_directory }}"
  become: yes

- name: Unmount Qt5 image
  command: hdiutil detach "{{ qt_volume_path }}"
  when: qt_volume_path_stat.stat.exists

- name: Install Qt5
  command: >
    {{ qt_app_directory }}/Contents/MacOS/{{ qt_installer_name }} --script roles/qt/files/qt-noninteractive.qs --platform minimal
    creates="/Applications/Qt{{ qt_version }}"
  become: yes
