---
- name: Install ruby-install
  shell: >
    chdir={{ downloads_directory }}
    wget -O "ruby-install-{{ ruby_install_version }}.tar.gz" "https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz" \
      && tar -xzvf "ruby-install-{{ ruby_install_version }}.tar.gz" \
      && cd "ruby-install-{{ ruby_install_version }}" \
      && sudo make install

- name: Install chruby
  shell: >
    chdir={{ downloads_directory }}
    wget -O "chruby-{{ chruby_version }}.tar.gz" "https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz" \
      && tar -xzvf "chruby-{{ chruby_version }}.tar.gz" \
      && cd "chruby-{{ chruby_version }}" \
      && sudo make install

- name: Install ruby
  command: ruby-install --system --no-download --no-reinstall ruby "{{ ruby_version }}" -- --enable-shared
